name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: cmake
      run: cmake -G Ninja -Bbuild
    - name: ninja
      run: ninja -C build
    - name: ninja test
      run: ninja -C build test
